[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bay_point_marketplace = "8NPWArWjjQthDGGLppygtwwSMtUtajt4jpzVsfu98RAo"

[programs.devnet]
bay_point_marketplace = "8NPWArWjjQthDGGLppygtwwSMtUtajt4jpzVsfu98RAo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./admin_bay1aCfaEwELREDGtadKov2S9CbkSHwLiBmtTo7Mp4u.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"